"""modified table

Revision ID: 067339c1e639
Revises: 485828b8e07b
Create Date: 2022-12-22 23:37:07.707445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067339c1e639'
down_revision = '485828b8e07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('result_url', sa.String(), nullable=True))
    op.drop_column('links', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('links', 'result_url')
    # ### end Alembic commands ###
