"""Добавлено поле status

Revision ID: 485828b8e07b
Revises: 704cd66fa4ee
Create Date: 2022-10-18 21:28:02.704295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485828b8e07b'
down_revision = '704cd66fa4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'status')
    # ### end Alembic commands ###
